packages:
  all:
    providers:
      c: [gcc@12.3.0, gcc@13.3.1, gcc@14.3.0, nvhpc@25.9, cce@21.0.0]
      cxx: [gcc@12.3.0, gcc@13.3.1, gcc@14.3.0, nvhpc@25.9, cce@21.0.0]
      fortran: [gcc@12.3.0, gcc@13.3.1, gcc@14.3.0, nvhpc@25.9, cce@21.0.0]
      blas: [cray-libsci, blis, openblas]
      lapack: [cray-libsci, openblas]
      mpi: [cray-mpich, openmpi]
      pkgconfig: [pkg-config]
    permissions:
      write: group
  gcc:
    externals:
    - spec: gcc@12.3.0 languages='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-12
          cxx: /usr/bin/g++-12
          fortran: /usr/bin/gfortran-12
        flags: {}
    - spec: gcc@13.3.1 languages='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-13
          cxx: /usr/bin/g++-13
          fortran: /usr/bin/gfortran-13
        flags: {}
    - spec: gcc@14.3.0 languages='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-14
          cxx: /usr/bin/g++-14
          fortran: /usr/bin/gfortran-14
        flags: {}
  cce:
    externals:
    - spec: cce@21.0.0
      prefix: /opt/cray/pe/cce/21.0.0
      extra_attributes:
        compilers:
          c: /opt/cray/pe/cce/21.0.0/bin/craycc
          cxx: /opt/cray/pe/cce/21.0.0/bin/craycxx
          fortran: /opt/cray/pe/cce/21.0.0/bin/crayftn
        flags: {}
  nvhpc:
    externals:
    - spec: nvhpc@25.9
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/25.9/compilers
      extra_attributes:
        compilers:
          c: /opt/nvidia/hpc_sdk/Linux_aarch64/25.9/compilers/bin/nvc
          cxx: /opt/nvidia/hpc_sdk/Linux_aarch64/25.9/compilers/bin/nvc++
          fortran: /opt/nvidia/hpc_sdk/Linux_aarch64/25.9/compilers/bin/nvfortran
        flags:
          cflags: --gcc-toolchain=/usr/bin/gcc-13
          cxxflags: --gcc-toolchain=/usr/bin/gcc-13
  castep:
    require:
    - "^openblas ^fftw"
  chapel:
    variants: comm=ofi host_platform=linux64 launcher=slurm-srun libfabric=spack
    require:
    - "%gcc"
  et:
    require:
    - "^openblas +ilp64 ^libint tune=et"
  namd:
    require:
    - "^charmpp@8.0.0 backend=ofi pmi=cray-pmi"
  numactl:
    require:
    - "%gcc"
  xz:
    require:
    - "%gcc"
  openmpi:
    variants: fabrics=ofi
  cray-fftw:
    buildable: false
    version: [3.3.10.11]
    externals:
    - spec: cray-fftw@3.3.10.11
      prefix: /opt/cray/pe/fftw/3.3.10.11/arm_grace
  cray-libsci:
    buildable: false
    version: [26.03.0]
    externals:
    - spec: cray-libsci@26.03.0 %gcc@12.3
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/26.03.0/GNU/12/aarch64
    - spec: cray-libsci@26.03.0 %gcc@13.3
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/26.03.0/GNU/12/aarch64
    - spec: cray-libsci@26.03.0 %gcc@14.3
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/26.03.0/GNU/12/aarch64
    - spec: cray-libsci@26.03.0 %nvhpc@25.9
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/26.03.0/NVIDIA/23.11/aarch64
    - spec: cray-libsci@26.03.0 %cce@21.0.0
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/26.03.0/CRAY/20.0/aarch64
  cray-mpich:
    buildable: false
    version: [9.1.0]
    externals:
    - spec: cray-mpich@9.1.0 %gcc@12.3
      prefix: /opt/cray/pe/mpich/9.1.0/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/2.3.1/lib64/
    - spec: cray-mpich@9.1.0 %gcc@13.3
      prefix: /opt/cray/pe/mpich/9.1.0/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/2.3.1/lib64/
    - spec: cray-mpich@9.1.0 %gcc@14.3
      prefix: /opt/cray/pe/mpich/9.1.0/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/2.3.1/lib64/
    - spec: cray-mpich@9.1.0 %cce@21.0.0
      prefix: /opt/cray/pe/mpich/9.1.0/ofi/crayclang/20.0
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/2.3.1/lib64/
    - spec: cray-mpich@9.1.0 %nvhpc@25.9
      prefix: /opt/cray/pe/mpich/9.1.0/ofi/nvidia/23.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/2.3.1/lib64/
  cuda:
    buildable: false
    version: [13.0]
    externals:
    - spec: cuda@13.0
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/25.9/cuda/13.0
  libfabric:
    buildable: false
    version: [2.3.1]
    externals:
    - spec: libfabric@2.3.1 fabrics=cxi
      prefix: /opt/cray/libfabric/2.3.1
      modules: [libfabric/2.3.1]
  cray-pmi:
    buildable: false
    version: [6.1.17]
    externals:
    - spec: cray-pmi@6.1.17
      prefix: /opt/cray/pe/pmi/6.1.17
      modules: [cray-pmi/6.1.17]
  python:
    buildable: false
    version: [3.12.12]
    externals:
    - spec: python@3.12.12
      prefix: /opt/cray/pe/python/3.12.12
      modules: [cray-python/3.12.12]
  autoconf:
    externals:
    - prefix: /usr
      spec: autoconf@2.69
  automake:
    externals:
    - prefix: /usr
      spec: automake@1.15.1
  binutils:
    externals:
    - prefix: /usr
      spec: binutils@2.45.0~gold~headers
  bison:
    externals:
    - prefix: /usr
      spec: bison@3.0.4
  cmake:
    externals:
    - prefix: /usr
      spec: cmake@3.28.3
  coreutils:
    externals:
    - prefix: /usr
      spec: coreutils@8.32
  curl:
    externals:
    - prefix: /usr
      spec: curl@8.14.1+gssapi+ldap+nghttp2
  diffutils:
    externals:
    - prefix: /usr
      spec: diffutils@3.6
  findutils:
    externals:
    - prefix: /usr
      spec: findutils@4.10.0
  flex:
    externals:
    - prefix: /usr
      spec: flex@2.6.4+lex
  gawk:
    externals:
    - prefix: /usr
      spec: gawk@4.2.1
  gettext:
    externals:
    - prefix: /usr
      spec: gettext@0.21.1
  git:
    externals:
    - prefix: /usr
      spec: git@2.51.0~tcltk
  gmake:
    externals:
    - prefix: /usr
      spec: gmake@4.2.1
  groff:
    externals:
    - prefix: /usr
      spec: groff@1.22.4
  libtool:
    externals:
    - prefix: /usr
      spec: libtool@2.4.6
  m4:
    externals:
    - prefix: /usr
      spec: m4@1.4.18
  openssh:
    externals:
    - prefix: /usr
      spec: openssh@9.6p1
  openssl:
    externals:
    - prefix: /usr
      spec: openssl@3.2.3
  perl:
    externals:
    - prefix: /usr
      spec: perl@5.26.1~cpanm+opcode+open+shared+threads
  pkg-config:
    externals:
    - prefix: /usr
      spec: pkg-config@0.29.2
  sed:
    externals:
    - prefix: /usr
      spec: sed@4.9
  subversion:
    externals:
    - prefix: /usr
      spec: subversion@1.14.1
  tar:
    externals:
    - prefix: /usr
      spec: tar@1.34
  zlib:
    externals:
    - prefix: /usr
      spec: zlib@1.2.13
