compilers:
- compiler:
    spec: gcc@=12.3.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: /usr/bin/g++-12
      f77: /usr/bin/gfortran-12
      fc: /usr/bin/gfortran-12
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=13.2.0
    paths:
      cc: /usr/bin/gcc-13
      cxx: /usr/bin/g++-13
      f77: /usr/bin/gfortran-13
      fc: /usr/bin/gfortran-13
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: cce@=17.0.1
    paths:
      cc: /opt/cray/pe/cce/17.0.1/bin/craycc
      cxx: /opt/cray/pe/cce/17.0.1/bin/craycxx
      f77: /opt/cray/pe/cce/17.0.1/bin/crayftn
      fc: /opt/cray/pe/cce/17.0.1/bin/crayftn
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@24.5
    paths:
      cc: /opt/nvidia/hpc_sdk/Linux_aarch64/24.5/compilers/bin/nvc
      cxx: /opt/nvidia/hpc_sdk/Linux_aarch64/24.5/compilers/bin/nvc++
      f77: /opt/nvidia/hpc_sdk/Linux_aarch64/24.5/compilers/bin/nvfortran
      fc: /opt/nvidia/hpc_sdk/Linux_aarch64/24.5/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: any
    modules: []

