compilers:
- compiler:
    spec: gcc@=12.3.0
    paths:
      cc: /opt/cray/pe/craype/default/bin/cc
      cxx: /opt/cray/pe/craype/default/bin/CC
      f77: /opt/cray/pe/craype/default/bin/ftn
      fc: /opt/cray/pe/craype/default/bin/ftn
    flags: {}
    operating_system: sles15
    target: aarch64
    modules:
    - craype-network-ofi
    - gcc-native/12.3
    - PrgEnv-gnu
    - craype-arm-grace
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@23.9
    paths:
      cc: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/compilers/bin/nvc
      cxx: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/compilers/bin/nvc++
      f77: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/compilers/bin/nvfortran
      fc: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: any
    modules: []
