packages:
  all:
    compiler: [gcc@12.3, gcc@13.2, gcc@14.2, nvhpc@24.11, cce@18.0.0, cce@18.0.0]
    providers:
      blas: [cray-libsci, blis]
      lapack: [cray-libsci, openblas]
      mpi: [cray-mpich, openmpi]
      pkgconfig: [pkg-config]
    variants: +cuda cuda_arch=90
    permissions:
      write: group
  numactl:
    require:
    - "%gcc"
  xz:
    require:
    - "%gcc"
  openmpi:
    variants: +cuda fabrics=ofi cuda_arch=90
  mpich:
    variants: +cuda+fortran~hydra pmi=cray device=ch4 netmod=ofi cuda_arch=90
  cray-libsci:
    buildable: false
    version: [24.07.0, 25.03.0]
    externals:
    - spec: cray-libsci@24.07.0 %gcc@12.3
      prefix: /opt/cray/pe/libsci/24.07.0/gnu/12.3/aarch64
    - spec: cray-libsci@24.07.0 %gcc@13.2
      prefix: /opt/cray/pe/libsci/24.07.0/gnu/13.2/aarch64
    - spec: cray-libsci@24.07.0 %nvhpc@23.9
      prefix: /opt/cray/pe/libsci/24.07.0/nvidia/23.11/aarch64
    - spec: cray-libsci@24.07.0 %cce@18.0.0
      prefix: /opt/cray/pe/libsci/24.07.0/cray/17.0/aarch64
    - spec: cray-libsci@25.03.0 %gcc@12.3
      prefix: /opt/cray/pe/libsci/25.03.0/gnu/12.3/aarch64
    - spec: cray-libsci@25.03.0 %gcc@13.2
      prefix: /opt/cray/pe/libsci/25.03.0/gnu/13.2/aarch64
    - spec: cray-libsci@25.03.0 %nvhpc@23.9
      prefix: /opt/cray/pe/libsci/25.03.0/nvidia/23.11/aarch64
    - spec: cray-libsci@25.03.0 %cce@18.0.0
      prefix: /opt/cray/pe/libsci/25.03.0/cray/17.0/aarch64
  cray-mpich:
    buildable: false
    version: [8.1.30, 8.1.32]
    externals:
    - spec: cray-mpich@8.1.30 %gcc@12.3
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
    - spec: cray-mpich@8.1.30 %gcc@13.2
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
    - spec: cray-mpich@8.1.30 %cce@18.0.0
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/cray/17.0
    - spec: cray-mpich@8.1.32 %gcc@12.3
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.22.0/lib64/
    - spec: cray-mpich@8.1.32 %gcc@13.2
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.22.0/lib64/
    - spec: cray-mpich@8.1.32 %cce@18.0.0
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/cray/17.0
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.22.0/lib64/
    - spec: cray-mpich@8.1.32 %nvhpc@23.9
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/nvidia/23.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.22.0/lib64/
  cuda:
    buildable: false
    version: [12.6.0]
    externals:
    - spec: cuda@12.6.0 %gcc
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/cuda/12.6/
    - spec: cuda@12.6.0 %cce
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/cuda/12.6/
  libfabric:
    buildable: false
    version: [1.22.0]
    externals:
    - spec: libfabric@1.22.0
      prefix: /opt/cray/libfabric/1.22.0/
      modules: [libfabric/1.22.0]
  cray-pmi:
    buildable: false
    version: [6.1.15]
    externals:
    - spec: cray-pmi@6.1.15
      prefix: /opt/cray/pe/pmi/6.1.15
      modules: [cray-pmi/6.1.15]
  python:
    version: [3.11.7]
    externals:
    - spec: python@3.11.7
      prefix: /opt/cray/pe/python/3.11.7
      modules: [cray-python/3.11.7]
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.43.1~gold~headers
      prefix: /usr
    - spec: binutils@2.41.0~gold~headers
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.28.3
      prefix: /usr
    - spec: cmake@3.20.4
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  curl:
    externals:
    - spec: curl@8.6.0+gssapi+ldap+nghttp2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21.1
      prefix: /usr
    - spec: gettext@0.20.2
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.0~tcltk
      prefix: /usr
    - spec: git@2.35.3~tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@9.6p1
      prefix: /usr
    - spec: openssh@8.4p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.1.4
      prefix: /usr
    - spec: openssl@1.1.1l-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+opcode+open+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.9
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.13
      prefix: /usr