packages:
  all:
    compiler: [gcc@12.3.0, nvhpc@24.9]
    providers:
      mpi: [openmpi, mpich]
    variants: +cuda cuda_arch=90
  numactl:
    require:
    - "%gcc"
  xz:
    require:
    - "%gcc"
  openmpi:
    variants: +cuda fabrics=ofi cuda_arch=90
  mpich:
    variants: +cuda+fortran pmi=pmix device=ch3 netmod=ofi cuda_arch=90
  cuda:
    buildable: false
    version: [12.2.0, 12.6.0]
    externals:
    - spec: cuda@12.2.0 %gcc
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/cuda/12.2
      modules: [cudatoolkit/23.9_12.2, craype-accel-nvidia90]
    - spec: cuda@12.2.0 %nvhpc
      prefix: /opt/nvidia/hpc_sdk/Linux_aarch64/23.9/cuda/12.2
      modules: [cudatoolkit/23.9_12.2]
    - spec: cuda@12.6.0 %gcc
      prefix: /home/brics/tgreen.brics/tests/opt/nvidia/hpc_sdk/Linux_aarch64/24.9/cuda/12.6/
      modules: [/home/brics/tgreen.brics/tests/opt/nvidia/hpc_sdk/modulefiles/nvhpc-byo-compiler/24.9]
    - spec: cuda@12.6.0 %nvhpc
      prefix: /home/brics/tgreen.brics/tests/opt/nvidia/hpc_sdk/Linux_aarch64/24.9/cuda/12.6/
      modules: [/home/brics/tgreen.brics/tests/opt/nvidia/hpc_sdk/modulefiles/nvhpc-byo-compiler/24.9]
  libfabric:
    buildable: false
    version: [1.15.2.0]
    externals:
    - spec: libfabric@1.15.2.0
      prefix: /opt/cray/libfabric/1.15.2.0
      modules: [libfabric/1.15.2.0]
  pmix:
    externals:
    - spec: pmix@4.2.6
      prefix: /usr
  git:
    externals:
    - spec: git@2.35.3~tcltk
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  curl:
    externals:
    - spec: curl@8.0.1+gssapi+ldap+nghttp2
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.41.0~gold~headers
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.13
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1l-fips
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.20.4
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.4p1
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  python:
    externals:
    - spec: python@3.6.15+bz2+crypt+ctypes~dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.20.2
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+opcode+open+shared+threads
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
