packages:
  all:
    compiler: [gcc@12.3, gcc@13.2, nvhpc@24.5, cce@17.0.1]
    providers:
      blas: [cray-libsci, blis, openblas]
      lapack: [cray-libsci, openblas]
      mpi: [cray-mpich, openmpi]
      pkgconfig: [pkg-config]
    permissions:
      write: group
  castep:
    prefer:
    - "^openblas ^fftw"
  et:
    require:
    - "^openblas +ilp64 threads=openmp ^libint tune=et"
  namd:
    require:
    - "^charmpp@8.0.0 backend=ofi pmi=cray-pmi"
  openmpi:
    variants: fabrics=ofi
  cray-libsci:
    buildable: false
    version: [24.03.0]
    externals:
    - spec: cray-libsci@24.03.0 %gcc@12.3
      modules: [cray-libsci/24.03.0]
      prefix: /opt/cray/pe/libsci/24.03.0/gnu/12.3/x86_64
    - spec: cray-libsci@24.03.0 %gcc@13.2
      modules: [cray-libsci/24.03.0]
      prefix: /opt/cray/pe/libsci/24.03.0/gnu/12.3/x86_64
    - spec: cray-libsci@24.03.0 %nvhpc@24.5
      modules: [cray-libsci/24.03.0]
      prefix: /opt/cray/pe/libsci/24.03.0/nvidia/23.3/x86_64
    - spec: cray-libsci@24.03.0 %cce@17.0.1
      modules: [cray-libsci/24.03.0]
      prefix: /opt/cray/pe/libsci/24.03.0/cray/17.0/x86_64
  cray-mpich:
    buildable: false
    version: [8.1.29]
    externals:
    - spec: cray-mpich@8.1.29 %gcc@12.3
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/lib64/
    - spec: cray-mpich@8.1.29 %gcc@13.2
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/lib64/
    - spec: cray-mpich@8.1.29 %nvhpc@23.9
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/nvidia/23.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/lib64/
    - spec: cray-mpich@8.1.29 %cce@17.0.1
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/cray/17.0
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/lib64/
  cray-pmi:
    buildable: false
    version: [6.1.14]
    externals:
    - spec: cray-pmi@6.1.14
      prefix: /opt/cray/pe/pmi/6.1.14
      modules: [cray-pmi/6.1.14]
      extra_attributes:
        environment:
          prepend_path:
            LIBRARY_PATH: /opt/cray/pe/pmi/6.1.14/lib 
  cuda:
    buildable: false
    version: [12.4.0]
    externals:
    - spec: cuda@12.4.0
      prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/24.5/cuda/12.4
  libfabric:
    buildable: false
    version: [1.20.1]
    externals:
    - spec: libfabric@1.20.1
      prefix: /opt/cray
      modules: [libfabric/1.20.1]
  autoconf:
    externals:
    - prefix: /usr
      spec: autoconf@2.69
  automake:
    externals:
    - prefix: /usr
      spec: automake@1.15.1
  binutils:
    externals:
    - prefix: /opt/cray/pe/cce/17.0.1/binutils/x86_64/x86_64-pc-linux-gnu
      spec: binutils@2.40~gold~headers
    - prefix: /usr
      spec: binutils@2.41.0~gold~headers
  bison:
    externals:
    - prefix: /usr
      spec: bison@3.0.4
  cmake:
    externals:
    - prefix: /usr
      spec: cmake@3.20.4
  coreutils:
    externals:
    - prefix: /usr
      spec: coreutils@8.32
  curl:
    externals:
    - prefix: /usr
      spec: curl@8.0.1+gssapi+ldap+nghttp2
  cvs:
    externals:
    - prefix: /usr
      spec: cvs@1.12.13
  diffutils:
    externals:
    - prefix: /usr
      spec: diffutils@3.6
  findutils:
    externals:
    - prefix: /usr
      spec: findutils@4.8.0
  flex:
    externals:
    - prefix: /usr
      spec: flex@2.6.4+lex
  gawk:
    externals:
    - prefix: /usr
      spec: gawk@4.2.1
  gettext:
    externals:
    - prefix: /usr
      spec: gettext@0.20.2
  git:
    externals:
    - prefix: /usr
      spec: git@2.35.3+tcltk
  gmake:
    externals:
    - prefix: /usr
      spec: gmake@4.2.1
  groff:
    externals:
    - prefix: /usr
      spec: groff@1.22.4
  libtool:
    externals:
    - prefix: /usr
      spec: libtool@2.4.6
  m4:
    externals:
    - prefix: /usr
      spec: m4@1.4.18
  openssh:
    externals:
    - prefix: /usr
      spec: openssh@8.4p1
  openssl:
    externals:
    - prefix: /usr
      spec: openssl@1.1.1l-fips
  perl:
    externals:
    - prefix: /usr
      spec: perl@5.26.1~cpanm+opcode+open+shared+threads
  pkg-config:
    externals:
    - prefix: /usr
      spec: pkg-config@0.29.2
  sed:
    externals:
    - prefix: /usr
      spec: sed@4.4
  subversion:
    externals:
    - prefix: /usr
      spec: subversion@1.14.1
  tar:
    externals:
    - prefix: /usr
      spec: tar@1.34
  zlib:
    externals:
    - prefix: /usr
      spec: zlib@1.2.13
